Pet-Tracker Front End Updates
mike-webster/pet-tracker pull request #59
Opened 2020-02-11 03:50 UTC by tony-opp

## PR Checklist
Front End Updates
- I updated the header/navigation menu/footer
- I updated the 'New Pet' and 'All Pets' pages so that the main content container is consistent
- Updated 'All Pets' page to show each pet as a card/tile (the button for each pet still needs to be re-linked)
- Made sure everything is mobile responsive
fix: 
- [ ] Updated documentation (if necessary)

2020-02-11 03:51 UTC, tony-opp commented
The Pet-Front-End branch was successfully merged with the master before creating this Pull Request.

2020-02-12 03:22 UTC, mike-webster requested changes
Just a couple minor things - everything else looks good!

2020-02-12 03:22 UTC, mike-webster commented on app/views/pet/index.html.erb
> -<div class="content">
Can you switch this back to 2 spaces for tabs as opposed to the 500 you seem to be using here? 😆

2020-02-12 03:22 UTC, mike-webster commented on app/views/pet/index.html.erb
> +              <a href="<%= new_pet_path %>" class="btn btn-secondary">more info</a>
Clicking on "more info" brings the user to create a new path? 🤔

2020-02-12 03:22 UTC, mike-webster commented on app/views/pet/new.html.erb
> +<div class="container mt-4">
Can you set the spacing back to 2 spaces here too?

2020-02-13 06:35 UTC, mike-webster commented
K. I'm just gonna do it for you 😄

2020-02-13 06:39 UTC, mike-webster approved these changes

2020-02-13 06:39 UTC, merged